 
import pandas as pd 
import concurrent.futures
import docker
import time
import datetime

import os
from docker_config import *

client = docker.from_env()

def get_time():
	currentDT = datetime.datetime.now()
	return '['+currentDT.strftime("%Y-%m-%d %H:%M:%S") +'] '

def process_container(url, id, script_name, container_timeout):
	## create and setup container ##
	print(get_time() + 'container_'+id+' creating!!')
	container_id  = client.containers.run(image=docker_image, name='container_'+id , volumes = vols,
										  shm_size='1G', user=docker_user, 
										  publish_all_ports=True,stdout=True, stderr=True, detach=True )
	print(get_time() + 'container_'+id+' created successfully!!')
	
	## wait for display to be activated ##
	time.sleep(10)

	## Execute javascript file
	print(get_time() +'container_'+id+': Executing javascript')
	container = client.containers.get('container_'+str(id))
	stats = container.stats(decode=True)	
	logs = container.exec_run(cmd=['node',script_name,url,id], user=docker_user,stdout=True, stderr=True, detach=True)
	time.sleep(container_timeout-20)
	print(get_time() +'container_'+id+': Execution complete!!')	
		
	if logs:
		return logs
	

def process_urls_parallel(urls, script_file, container_timeout, max_containers):
	futures={}
	count=0
	processed_url_ids = []
	with concurrent.futures.ThreadPoolExecutor(max_workers = max_containers) as executor:
		while len(urls)>0:
			## Submit jobs to container ##
			for i in range(min(len(urls),max_containers)):
				id = urls.keys()[0]
				url = urls.pop(id)
				futures[executor.submit(process_container, url, str(id), script_file, container_timeout)] = id
		
			## Remove containers that are unused  ##
			try:
				client.containers.prune()		
			except Exception as e:
				print e						
			res_futures = concurrent.futures.wait(futures, timeout=container_timeout, return_when= concurrent.futures.ALL_COMPLETED)
			#print(res_futures)
			for future in res_futures[0]:
				id = futures.pop(future)				
				try:
					log = future.result(timeout=container_timeout)
					if os.path.exists('./logs/permission_'+str(id)+'.log'):
						print (get_time() + 'Container_'+ str(id) +': Completed successfully!!'	)
						processed_url_ids.append(id)		
				except Exception as exc:
					print(get_time() +  'Container_' + str(id) +': Exception ')
					print(exc)	
				client.containers.get('container_'+str(id)).stop()
				client.containers.get('container_'+str(id)).remove()
			for future in res_futures[1]:
				id =  futures.pop(future)						
				print(get_time() +  'Container_' + str(id) +': Timeout occured!!')	
				client.containers.get('container_'+str(id)).stop()
				client.containers.get('container_'+str(id)).remove()									
			
	return processed_url_ids


def stop_running_containers():
	while client.containers.list():		
		for c in client.containers.list():
			print (c)			
			c.stop()
			c.remove()

def fetch_urls_for_crawling():
	urls = ['https://www.taxheaven.gr/',				
	'https://www.gizbot.com/',
				'https://pagead2.googlesyndication.com/pagead/s/cookie_push.html#aHR0cHM6Ly9weC5vd25lcmlxLm5ldC9lY21nP2dvb2dsZV9naWQ9Q0FFU0VCaTh6ODkyUERpb0RwVnFUT3JhakJNJmdvb2dsZV9jdmVyPTEmZ29vZ2xlX3B1c2g9QUhORjEzS0hoSXYybU1kdDM5SThINmhReVBWblJXd0hGUmQ1dlJnZWxqVlQ',
				'https://www.alitalia.com/it_it',
				'https://www.eleman.net/',
				'https://www.mcdonalds.com/gb/en-gb.html',
				'https://www.sendo.vn/',
				'https://www.fullprogramlarindir.com/',
				'https://alpari.com/',
				'https://socialnewpagessearch.com/',
				'https://image4.pubmatic.com/AdServer/SPug?partnerID',
				'https://tpc.googlesyndication.com/safeframe/1-0-32/html/container.html',
				'https://googleads.g.doubleclick.net/pagead/html/r20190306/r20190131/zrt_lookup.html#RS-1-&adk',
				'https://www.costco.ca/',
				'https://meduza.io/',
				'https://www.myjobmag.com/',
				'https://allo.ua/',
				'https://news.sportbox.ru/',
				'https://pixel.mathtag.com/sync/iframe?mt_uuid',
				'https://www.idntimes.com/',
				'https://www.weekendhk.com/',
				'https://www.barclays.co.uk/',
				'https://www.fux.com/',
				'https://hinkhoj.com/',
				'https://healthylives.tw/',
				'https://s0.2mdn.net/8296704/1549316500985/index.html',
				'https://www.hardsextube.com/',
				'https://www.ebay.co.uk/',
				'https://www.rt.com/',
				'https://www.ebay.com/signin/id',
				'https://www.cardekho.com/',
				'https://draxe.com/',
				'https://www.zigwheels.com/',
				'https://tpc.googlesyndication.com/safeframe/1-0-32/html/container.html',
				'https://www.peixeurbano.com.br/',
				'https://stocks.thehindubusinessline.com/BseNse_Ticker.aspx',
				'https://imperiya.by/',
				'https://www.parsonline.com/',
				'https://googleads.g.doubleclick.net/pagead/ads?client',
				'https://www.thehindu.com/',
				'https://www.photographytalk.com/',
				'https://www.porntube.com/',
				'https://www.4tube.com/',
				'https://ruposters.ru/',
				'https://www.hellomagazine.com/',
				'https://www.futura-sciences.com/',
				'https://mirrorace.com/',
				'https://www.hespress.com/',
				'https://www.gametwist.com/en/',
				'https://www.chetor.com/',
				'https://www.qoo10.sg/?__ar',
				'https://www.cyberlink.com/index_en_GB.html?r',
				'https://www.sinemalar.com/',
				'https://www.medi1tv.ma/ar/',
				'https://tvrain.ru/',
				'https://www.priceza.com/',
				'https://www.santander.com.br/',
				'https://www.dnaindia.com/',
				'https://www.avito.ma/',
				'https://www.pornerbros.com/',
				'https://matchtv.ru/',
				'https://www.okanime.com/',
				'https://www.haaretz.co.il/',
				'https://www.ebay.fr/',
				'https://www.geo.tv/',
				'https://tubedupe.com/',
				'https://www.jobs77.com/',
				'https://tpc.googlesyndication.com/safeframe/1-0-32/html/container.html',
				'https://www.realmadrid.com/en',
				'https://funsafetabsearch.com/',
				'https://ads.pubmatic.com/AdServer/js/showad.js#PIX&kdntuid',
				'https://www.vedomosti.ru/',
				'https://widgets.outbrain.com/widgetOBUserSync/obUserSync.html#pid',
				'https://tpc.googlesyndication.com/safeframe/1-0-32/html/container.html',
				'https://www.sarvgyan.com/',
				'https://f1-gate.com/',
				'https://tpc.googlesyndication.com/safeframe/1-0-32/html/container.html',
				'https://www.tkec.com.tw/index.aspx',
				'https://www.plaisio.gr/',
				'https://znaj.ua/',
				'https://www.filmibeat.com/',
				'https://www.youtube.com/embed/?controls',
				'https://www.300mbfilms.co/',
				'https://amctheatres.com/',
				'https://zhaket.com/',
				'https://www.toprankers.com/',
				'https://imasdk.googleapis.com/js/core/bridge3.285.0_en.html#goog_1335060106',
				'https://www.carwale.com/',
				'https://www.madeeasy.in/',
				'https://www.absa.co.za/personal/',
				'https://googleads.g.doubleclick.net/pagead/ads?client',
				'https://www.ae.com/',
				'https://www.chotot.com/',
				'https://newtab-tvsearch.com/',
				'https://topbanger.com/',
				'https://vesti-ukr.com/',
				'https://www.tinkoff.ru/',
				'https://pimpandhost.com/',
				'https://medianewpagesearch.com/',
				'https://www.r7.com/',
				'https://www.skynewsarabia.com/',
				'https://www.caasimada.net/',
				'https://soft98.ir/',
				'https://stirileprotv.ro/',
				'https://ethereumprice.org/',
				'https://us.hola.com/',
				'https://menhdv.com/',
				'https://www.youtube.com/',
'https://www.twitch.tv/',
'https://www.pornhub.com/',
'https://www.ebay.com/',
'https://mail.ru/',
'https://www.wikia.com/explore',
'https://www.tumblr.com/',
'https://www.dropbox.com/',
'https://www.bbc.co.uk/',
'https://www.thestartmagazine.com/feed/summary',
'https://www.nicovideo.jp/',
'https://www.cnn.com/',
'https://www.bbc.com/',
'https://www.zhihu.com/signup?next=%2F',
'https://www.dailymotion.com/',
'https://www.ebay.co.uk/',
'https://www.alibaba.com/',
'https://www.mercadolivre.com.br/',
'https://www.scribd.com/',
'https://www.redtube.com/',
'https://www.indiatimes.com/',
'https://weather.com/en-GB/',
'https://www.blackboard.com/index.html',
'https://www.speedtest.net/',
'https://9gag.com/',
'https://www.livejournal.com/',
'https://www.freepik.com/',
'https://www.gamespot.com/',
'https://www.varzesh3.com/',
'https://allegro.pl/',
'https://www.kinopoisk.ru/',
'https://www.rt.com/',
'https://www.businessinsider.com/international?r=US&IR=T',
'https://www.hola.com/',
'https://www.flickr.com/',
'https://www.box.com/',
'https://www.ndtv.com/',
'https://www.mercadolibre.com.ar/',
'https://www.ign.com/',
'https://www.theepochtimes.com/',
'https://uidai.gov.in/',
'https://www.uptodown.com/',
'https://www.wix.com/',
'http://web.mit.edu/',
'https://zoom.us/',
'https://www.repubblica.it/',
'https://www.thebalance.com/',
'https://bleacherreport.com/',
'https://slickdeals.net/',
'https://www.mercadolibre.com.mx/',
'https://ria.ru/',
'https://sabq.org/',
'https://www.ebay.com.au/',
'https://www.investing.com/',
'https://www.kapanlagi.com/',
'http://www.hurriyet.com.tr/',
'https://quizlet.com/',
'https://readms.net/',
'https://www.gosuslugi.ru/',
'https://www.anastasiadate.com/',
'https://www.urbandictionary.com/',
'https://www.eventbrite.com/',
'https://www.xda-developers.com/',
'https://www.expedia.com/',
'https://www.japanpost.jp/',
'https://www.idntimes.com/',
'https://www.sindonews.com/',
'https://www.corriere.it/',
'https://www.marketwatch.com/',
'https://www.engadget.com/',
'https://www.givemesport.com/',
'https://www.yenisafak.com/',
'https://www.grammarly.com/',
'https://www.vidio.com/',
'https://kumparan.com/',
'http://www.freejobalert.com/',
'https://www.hespress.com/',
'https://www.flirt4free.com/',
'https://www.rbc.ru/',
'https://tabelog.com/',
'https://www.tube8.com/',
'https://www.ebay.fr/',
'https://www.y8.com/',
'https://www.bhphotovideo.com/',
'https://shop.nordstrom.com/',
'https://deadspin.com/',
'https://www.ecosia.org/',
'https://bitly.com/',
'https://www.ruten.com.tw/',
'https://www.discuss.com.hk/',
'https://dribbble.com/',
'https://study.com/',
'https://worldoftanks.ru/',
'https://www.costco.com/',
'https://mawdoo3.com/',
'https://www.thoughtco.com/',
'https://www.welt.de/',
'https://www.makemytrip.com/',
'https://www.schwab.com/',
'https://www.dawn.com/',
'https://www.allrecipes.com/',
'https://fishki.net/',
'https://www.wowhead.com/',
'http://www.myanmarload.com/',
'https://www.hepsiburada.com/',
'https://www.weather.gov/',
'https://steemit.com/',
'https://www.avito.ma/',
'https://www.hltv.org/',
'https://www.postbank.de/',
'https://www.plex.tv/',
'https://www.bhaskar.com/',
'https://www.uber.com/gb/en/',
'https://www.thehindu.com/',
'https://www.telekom.com/en',
'https://www.gazzetta.it/',
'https://www.change.org/',
'https://www.drtuber.com/',
'https://www.pcmag.com/',
'https://www.farfetch.com/uk/',
'https://in.bookmyshow.com/',
'https://www.gittigidiyor.com/',
'https://www.123rf.com/',
'https://www.lequipe.fr/',
'http://www.jawabkom.com/',
'https://www.nintendo.com/',
'https://www.ashemaletube.com/',
'https://eu.wargaming.net/',
'https://www.heise.de/',
'https://www.ebay.ca/',
'https://xhamsterlive.com/',
'https://www.flaticon.com/',
'http://sozcu.com.tr/',
'https://www.g2a.com/',
'https://start.att.net/',
'https://www.oneindia.com/',
'https://gaana.com/',
'https://www.jstor.org/',
'https://www.20minutes.fr/',
'https://www.thingiverse.com/',
'https://www.leo.org/german-english',
'https://www.zeit.de/index',
'https://nptel.ac.in/',
'https://solarmoviez.ru/',
'https://www.elbotola.com/',
'http://www.caf.fr/',
'http://www.axisbank.com/',
'https://www.tripadvisor.co.uk/',
'http://www.yeniakit.com.tr/',
'https://www.linternaute.com/',
'https://jalopnik.com/',
'https://www.cdc.gov/',
'https://stripe.com/gb',
'https://www.tut.by/',
'https://www.zdf.de/',
'https://www.cryptocompare.com/',
'https://www.letras.mus.br/',
'https://www.bola.net/',
'https://www.avclub.com/',
'http://www.notification.team/',
'https://www.sap.com/index.html',
'https://www.ziprecruiter.com/',
'http://www.surrenderat20.net/',
'http://www.furaffinity.net/',
'https://porndoe.com/',
'https://www.kohls.com/',
'https://www.smartadtags.com/en/',
'https://www.webgains.com/public/en/',
'https://pngtree.com/',
'https://www.collegeboard.org/',
'https://www.sky.com/',
'https://www.skroutz.gr/',
'https://www.ilfattoquotidiano.it/',
'https://www.xero.com/uk/',
'https://www.sports.ru/',
'https://www.sport-express.ru/',
'https://www.hsbc.com.hk/',
'https://newtabtvsearch.com/',
'https://www.medscape.com/',
'http://www.playground.ru/',
'https://www.hsbc.co.uk/',
'https://www.pearson.com/uk/',
'http://www.sbi.co.in/',
'https://www.mercadolibre.com.co/',
'https://www.ria.com/',
'https://www.inc.com/',
'https://rg.ru/',
'https://www.futhead.com/',
'https://www.wetter.com/',
'https://www.nuvid.com/',
'https://www.onliner.by/',
'https://www.ny.gov/',
'https://www.nutaku.net/',
'http://www.cracked.com/',
'https://healthy.kaiserpermanente.org/',
'https://www.emag.ro/',
'https://www.17173.com/',
'https://www.emirates.com/uk/english/',
'https://www.marktplaats.nl/',
'https://www.greenhouse.io/',
'https://www.cargurus.com/',
'https://www.kantipurdaily.com/',
'https://tunein.com/',
'http://www.kalerkantho.com/',
'https://en.downloadastro.com/',
'https://scroll.in/',
'https://www.apartments.com/',
'https://tirto.id/',
'https://www.hotnewhiphop.com/',
'https://www.shopclues.com/',
'https://streamlabs.com/',
'https://www.avira.com/',
'https://myetherwallet.com/',
'https://os.tc/',
'https://www.bankbazaar.com/',
'https://www.directv.com/',
'https://www.ana.co.jp/en/jp/?type=e',
'https://www.blocket.se/',
'https://www.pipedrive.com/en-gb',
'https://www.bitfinex.com/',
'https://meduza.io/',
'https://www.4tube.com/',
'https://nnovgorod.rt.ru/',
'http://dunyanews.tv/',
'https://hitbtc.com/',
'https://www.hitc.com/',
'https://www.hotukdeals.com/',
'https://www.kaspersky.com/',
'https://www.chefkoch.de/',
'https://www.tesco.com/',
'https://www.tableau.com/',
'https://tiu.ru/',
'http://www.myshared.ru/',
'https://www.filmibeat.com/',
'https://www.hindustantimes.com/',
'https://soft98.ir/',
'http://literotica.com/',
'https://www.cimbclicks.com.my/',
'https://www.elnuevodiario.com.ni/',
'https://www.kommersant.ru/',
'http://www.yinyuetai.com/',
'https://www.abplive.in/',
'https://gradeup.co/',
'http://www.tgju.org/',
'https://baomoi.com/',
'https://www.ing-diba.de/',
'https://www.lepoint.fr/',
'https://www.check24.de/',
'https://www.yoox.com/uk',
'https://www.education.com/',
'https://www.mercadolibre.cl/',
'https://www.kraken.com/',
'https://jezebel.com/',
'https://www.immobiliare.it/',
'https://splinternews.com/',
'https://uwaterloo.ca/',
'https://www.porntube.com/',
'https://foodeliciouz.com/',
'https://worldoftanks.com/',
'https://www.edmunds.com/',
'https://www.massdrop.com/',
'http://licindia.in/',
'https://www.freepik.es/',
'https://www.indiapost.gov.in/vas/Pages/IndiaPostHome.aspx',
'https://www.ozbargain.com.au/',
'https://www.revistaforum.com.br/',
'https://thechive.com/',
'http://slideplayer.com/',
'https://news.sportbox.ru/',
'https://wpengine.com/',
'https://www.superjob.ru/',
'https://www.theroot.com/',
'https://www.dealabs.com/',
'https://www.eldorado.ru/',
'https://bama.ir/',
'https://www.complex.com/',
'https://www.zoopla.co.uk/',
'https://www.sport24.gr/',
'https://www.sarvgyan.com/',
'https://www.airbnb.co.uk/',
'https://cryptowat.ch/',
'http://www.hani.co.kr/',
'https://www.price.com.hk/',
'https://www.barclays.co.uk/',
'https://www.dek-d.com/',
'https://www.nab.com.au/',
'https://www.ford.com/',
'https://www.gog.com/',
'https://www.mixcloud.com/',
'https://www.shareae.com/',
'http://www.inbox.lv/',
'https://www.joinhoney.com/',
'https://www.tes.com/',
'https://screenrant.com/',
'http://www.dikaiologitika.gr/',
'https://www.ebay.ie/',
'https://nest.com/',
'https://megogo.net/ru',
'https://www.giantbomb.com/',
'https://presslogic.com/',
'https://www.ae.com/',
'https://www.tipico.de/en/online-sports-betting/',
'https://en.zalando.de/',
'https://www.aviasales.ru/',
'https://www.standard.co.uk/',
'https://www.cibc.com/en/personal-banking.html',
'https://zaif.jp/',
'https://www.vitalsource.com/',
'https://www.windowscentral.com/',
'https://www.c-sharpcorner.com/',
'https://www.fastcompany.com/',
'https://handy-tab.com/',
'https://www.heureka.cz/',
'https://globalnews.ca/',
'https://pdf2doc.com/',
'https://www.couchsurfing.com/',
'https://www.kotak.com/en.html',
'https://manofile.com/',
'https://www.tripadvisor.fr/',
'https://www.sofascore.com/',
'https://www.usajobs.gov/',
'https://www.giga.de/',
'http://www.oyunskor.com/',
'https://www.newgrounds.com/',
'https://www.rentalcars.com/',
'https://draxe.com/',
'https://www.picmonkey.com/',
'https://worldoftanks.eu/',
'https://tinhte.vn/',
'https://www.bankrate.com/',
'http://www.juegos.com/',
'https://www.bestbuy.ca/',
'https://www.pornoxo.com/',
'https://www.qoo10.sg/?__ar=Y',
'https://www.blick.ch/',
'https://www.mathway.com/',
'https://www.shine.com/',
'https://www.kanald.com.tr/',
'https://www.carwale.com/',
'https://www.saramin.co.kr/zf_user/',
'https://www.travelocity.com/',
'https://www.westernunion.com/gb/en/home.html',
'https://www.airbnb.fr/',
'https://wileyplus.com/',
'https://www.thetrainline.com/',
'https://www.walla.co.il/',
'https://nios.ac.in/',
'https://bgr.com/',
'https://www.cardekho.com/',
'https://www.santander.com.br/',
'https://www.20min.ch/',
'https://www.cool3c.com/',
'https://www.novelupdates.com/',
'https://qoolquiz.com/',
'https://www.sleazyneasy.com/',
'https://www.imore.com/',
'https://www.rockpapershotgun.com/',
'https://www.ableton.com/',
'https://www.androidpolice.com/',
'https://texas.gov/',
'https://www.theonion.com/',
'https://beautyexchange.com.hk/',
'https://blackdoctor.org/',
'https://www.vultr.com/',
'https://www.masrawy.com/',
'https://www.seloger.com/',
'http://theconversation.com/uk',
'https://localbitcoins.com/',
'https://www.governmentjobs.com/',
'https://vsco.co/',
'https://crowdworks.jp/',
'https://www.work.ua/',
'https://www.24sata.hr/',
'https://www.iefimerida.gr/',
'http://www.akhbarak.net/',
'https://www.canadapost.ca/cpc/en/home.page',
'https://kolesa.kz/',
'https://www.obozrevatel.com/',
'https://onesignal.com/',
'http://netbarg.com/',
'https://www.2dehands.be/',
'https://www.jotform.com/',
'http://www.transfermarkt.de/',
'https://www.eventbrite.co.uk/',
'https://www.freshersworld.com/',
'https://tfl.gov.uk/',
'https://laracasts.com/',
'https://www.1800flowers.com/?utm_medium=direct&utm_source=1800flowerscom',
'https://www.faceit.com/',
'https://www.boyfriendtv.com/',
'https://internshala.com/',
'https://www.telegraaf.nl/',
'https://www.statefarm.com/',
'https://www.mercadolibre.com.pe/',
'https://trinixy.ru/',
'https://www.battlenet.com.cn/zh/',
'https://www.frontiersin.org/',
'https://icai.org/',
'https://www.itv.com/',
'https://www.rawstory.com/',
'https://www.bible.com/',
'https://eu.mouser.com/',
'https://www.jawharafm.net/ar/',
'https://ura.news/',
'https://www.timesofmalta.com/',
'https://my.com/',
'https://www.wonderhowto.com/',
'https://www.webstaurantstore.com/',
'https://www.cabelas.com/',
'https://www.atlasobscura.com/',
'http://gravitytales.com/',
'https://thepointsguy.com/',
'https://www.ifanr.com/',
'https://www.jetstar.com/au/en/home',
'https://www.divyabhaskar.co.in/',
'https://www.lyst.com/',
'https://facenama.com/',
'https://www.zigwheels.com/',
'https://cont.ws/',
'http://buffstreamz.com/',
'https://www.thestudentroom.co.uk/',
'https://mahendras.org/',
'http://iitk.ac.in/',
'http://www.fixya.com/',
'http://ignou.ac.in/',
'https://www.nelnet.com/welcome',
'https://www.news247.gr/',
'https://www.medi1tv.ma/ar/',
'https://www.mydirtyhobby.com/',
'https://www.beforward.jp/',
'https://www.joyclub.de/',
'https://airtable.com/',
'https://www.ant.com/',
'https://en.jav101.com/',
'https://uconn.edu/',
'https://www.eleman.net/',
'http://tappedout.net/',
'https://www.wufoo.com/',
'https://www.futura-sciences.com/',
'https://www.fluentu.com/',
'https://www.almasryalyoum.com/',
'https://www.livemint.com/',
'https://www.blesk.cz/',
'https://www.optimum.net/',
'https://www.eurosport.ru/',
'https://www.bell.ca/',
'http://www.ni.com/en-us.html',
'https://www.dice.com/',
'http://ancensored.com/',
'https://www.tinkoff.ru/',
'https://www.remind.com/',
'https://www.expedia.co.jp/',
'https://www.webnovel.com/',
'https://www.op.fi/',
'https://kanobu.ru/',
'https://www.aarp.org/',
'https://www.mcdonalds.com/gb/en-gb.html',
'https://letyshops.com/uk',
'https://www.formstack.com/',
'https://www.soft112.com/',
'https://www.aircanada.com/ca/en/aco/home.html',
'https://www.topbuzz.com/',
'https://www.bungie.net/',
'https://matchtv.ru/',
'http://bdjobs.com/',
'http://www.gnu.org/',
'https://www.channelnewsasia.com/',
'https://www.theodysseyonline.com/',
'https://www.yektanet.com/',
'https://www.tensorflow.org/',
'https://my.avon.ru/',
'https://sbi-recruitment.in/',
'https://www.4kdownload.com/',
'https://www.2ememain.be/',
'https://www.honda.com/',
'https://www.heureka.sk/',
'https://www.anten.ir/',
'https://www.vcu.edu/',
'https://www.ringcentral.com/',
'https://www.airdroid.com/',
'https://www.katestube.com/',
'https://www2.telenet.be/nl',
'https://www.xm.com/',
'https://mdpr.jp/',
'https://www.jbhifi.com.au/',
'https://healthylives.tw/',
'http://www.profitguruonline.com/',
'https://www.hackerearth.com/',
'https://www.pgatour.com/',
'https://socialnewpagessearch.com/',
'https://hvg.hu/',
'https://www.airbnb.it/',
'https://rp-online.de/',
'http://asrb.org.in/',
'http://dunya.com.pk/',
'https://www.gate.io/',
'https://www.apkmirror.com/',
'https://www.mytheresa.com/',
'https://swedbank.se/',
'http://www.agame.com/',
'http://www.delfi.ee/',
'https://www.absa.co.za/personal/',
'https://ecnavi.jp/',
'https://www.taxheaven.gr/',
'https://uk.pandora.net/en',
'https://jpg2pdf.com/',
'https://www.jobkorea.co.kr/',
'http://mponline.gov.in/portal/',
'https://www.11street.my/',
'https://www.r7.com/',
'https://wikium.ru/',
				]
	start_id = 1000
	#urls = ['https://blacktv.tk/']
	crawl_urls = {start_id+i:url for i,url in enumerate(urls) }
	return crawl_urls

def crawl_urls_for_permission_requests():
	crawl_urls = fetch_urls_for_crawling()
	processed_urls = process_urls_parallel(crawl_urls, permission_collection_script, CRAWL_TIMEOUT, CRAWL_MAX_CONTAINERS)
	print(processed_urls)
	return True


def main():	
	stop_running_containers()
	crawl_urls_for_permission_requests()

if __name__ == "__main__":
    main()
